version: '3'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./v2fly4.vless-vmess-trojan-shadowsocks/nginx/conf.d:/etc/nginx/conf.d"
      - "./v2fly4.vless-vmess-trojan-shadowsocks/nginx/certs:/etc/nginx/certs"
      - "./v2fly4.vless-vmess-trojan-shadowsocks/nginx/nginx.conf:/etc/nginx/nginx.conf"
    container_name: nginx

  v2fly:
    restart: always
    depends_on:
      - nginx
    image: v2fly/v2fly-core:v4.45.2
    volumes:
      - "./v2fly4.vless-vmess-trojan-shadowsocks/v2fly/config.json:/etc/v2ray/config.json"
      - "./v2fly4.vless-vmess-trojan-shadowsocks/nginx/certs:/cert/"
    container_name: v2fly
