version: '3'
services: 
    nginx: 
        image: nginx:latest
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes: 
            - "./v2fly4.vless-vmess-trojan/nginx/conf.d:/etc/nginx/conf.d"
            - "./v2fly4.vless-vmess-trojan/nginx/certs:/etc/nginx/certs"
            - "./v2fly4.vless-vmess-trojan/nginx/nginx.conf:/etc/nginx/nginx.conf"
        container_name: nginx

    vless:
        restart: always
        depends_on:
            - nginx
        image: v2fly/v2fly-core:v4.45.2
        volumes: 
            - "./v2fly4.vless-vmess-trojan/v2fly_vless/config.json:/etc/v2ray/config.json"
            - "./v2fly4.vless-vmess-trojan/nginx/certs:/etc/v2ray/certs"
        container_name: vless

    vmess:
        restart: always
        depends_on:
            - nginx
        image: v2fly/v2fly-core:v4.45.2
        volumes:
            - "./v2fly4.vless-vmess-trojan/v2fly_vmess/config.json:/etc/v2ray/config.json"
            - "./v2fly4.vless-vmess-trojan/nginx/certs:/etc/v2ray/certs"
        container_name: vmess

    trojan:
        image: p4gefau1t/trojan-go
        restart: always
        volumes:
            - "./v2fly4.vless-vmess-trojan/nginx/certs:/cert/"
            - "./v2fly4.vless-vmess-trojan/trojan/config.json:/etc/trojan-go/config.json"
        depends_on:
            - nginx
        container_name: trojan
